agrant.configure("2") do |config|

#1
  config.vm.define "ubuntu" do |ubuntu|
   ubuntu.vm.box = "ubuntu/bionic64"
     ubuntu.vm.provision "shell",
#2   
      inline:
      "apt-get update"


#3
   config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
     centos.vm.provision "shell",
#4      
      inline:
       "sudo yum update
         sudo yum install -y httpd
	 mkdir Tychyna "

#5  
     centos.vm.network "forwarded_port", guest: 80, host: 8080
     end

end

