FROM mysql:5.7


MAINTAINER <yura66778@gmail.com>


ENV MYSQL_ROOT_PASSWORD="rootyura"

ENV MYSQL_DATABASE="tychyna"

ENV MYSQL_USER: "yura2121"

ENV MYSQL_PASSWORD: "yura"

RUN mysql 
EXPOSE 3306
